### PR TITLE
Correct CST (China Standard Time) to UTC+8

### PR DESCRIPTION
**Pull request by yfdyh000**
I hope the CST is no conflict and works for all.

I hope this has a common conversion library, or identify its source.

### CODE REVIEW

**Comment by yfdyh000** [comment]
@Rik

**Comment by yfdyh000** [comment]
@gkoberger

**Comment by yfdyh000** [comment]
@mnoorenberghe

**Comment by mnoorenberghe** [comment]
This will conflict with https://en.wikipedia.org/wiki/Central_Standard_Time

(I haven't yet looked how these definitions are used)

**Comment by yfdyh000** [comment]
STR:
Set the "Timezone used to display dates and times" to "Asia/Shanghai" on https://bugzilla.mozilla.org/userprefs.cgi?tab=settings.

I see the "CDT" when "America/Chicago" was set for now.

**Comment by mnoorenberghe** [comment]
> I see the "CDT" when "America/Chicago" was set for now.

That's because they just switched to CDT due to daylight savings time a few weeks ago. It will switch back to CST in the fall.

**Comment by yfdyh000** [comment]
Ah, I also suspect but have not seen the CST for it, and I did not find the relevant definitions in Bugzilla source.

**Comment by mnoorenberghe** [comment]
Please re-open if you have a new patch that doesn't conflict with Central Standard Time.

**Pull request closed without merging**
